<<<<<<< HEAD
theme = "ayu_evolve"
=======
theme = "transparent_ayu_evolve"
>>>>>>> 90805a594426d34d79453e0d4a1214dc505ab542

[editor]
line-number = "relative"
mouse = true
cursorline = true
cursorcolumn = false
bufferline = "multiple"
auto-pairs = true
color-modes = true
auto-completion = true
true-color = true
completion-trigger-len = 2


[editor.file-picker]
hidden = false

[keys.insert] 
j = {j = "normal_mode"} 

[keys.normal]
C-g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]
C-b = "no_op"


[keys.select]
C-b = "no_op"

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "block"

[editor.indent-guides]
render = true
character = "|"

[editor.soft-wrap]
enable = true
wrap-indicator = ''

[editor.statusline]
left = [ "mode", "spinner", "diagnostics" ]
center = [ "file-name", "separator", "version-control" ]
right = [ "position", "position-percentage", "total-line-numbers" ]
separator = " | "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
auto-signature-help = false
    
