theme = "transparent_gruvbox"

[editor]
line-number = "relative"
mouse = true
cursorline = true
cursorcolumn = false
bufferline = "multiple"
auto-pairs = true
color-modes = true
auto-completion = false
true-color = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"

[editor.file-picker]
hidden = false

[keys.insert] 
j = {j = "normal_mode"} 

[keys.normal]
C-g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "block"

[editor.indent-guides]
render = true
character = "."

[editor.soft-wrap]
enable = true
wrap-indicator = ''

[editor.statusline]
left = [ "mode", "spinner", "diagnostics" ]
center = [ "file-name", "separator", "version-control" ]
right = [ "position", "position-percentage", "total-line-numbers" ]
separator = " | "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
auto-signature-help = true
display-messages = true

