
# name = "python"
# # auto-format = true
# language-servers = [ "pyright", "ruff" ]

# [language-server.pyright.config.python.analysis]
# typeCheckingMode = "basic"

# [language-server.ruff]
# command = "ruff-lsp"

# [language-server.ruff.config.settings]
# args = ["--ignore", "E501"]

# [language.formatter]
# command = "black"
# args = ["--line-length", "88", "--quiet", "-"]

# [[language]]
# name = "python"
# auto-format = true
# #language-servers = ["pyright","ruff", "mypy", "pylsp"]
# language-servers = ["pylsp", "pyright"]

# [language-server.pyright]
# command = "pyright-langserver"
# args = ["--stdio"] 

# # [language-server.ruff]
# # command = "ruff"
# # args = ["server"]


# [language-server.pylsp.config.pylsp]
# plugins.pylsp_mypy.enabled = true
# plugins.pylsp_mypy.live_mode = true


# [language-server.pylsp.config.pylsp.plugins.pyflakes]
# enabled = true
# # Note: pylsp plugin overrides vary; alternatively disable pyflakes if it persists



[[language]]
name = "python"
auto-format = true
language-servers = [
    {name = "pyright"},
    {name = "ruff"},
    {name = "mypy"}
]
formatter = { command = "ruff", args = ["format", "-"] }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.settings.python.analysis]
diagnosticSeverityOverrides = { "reportUnusedImport" = "none" }

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings.lint]
ignore = [ "F401", "I001", "DTZ005" ]
